version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: restfulladminactivos
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres_data:
